services:
  postgres:
    image: postgres:13
    container_name: kraken-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  airflow:
    build:
      context: .
      dockerfile: docker/airflow.Dockerfile
    container_name: kraken-airflow
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__WEBSERVER__RBAC=True
      - PYTHONPATH=/opt/airflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./scripts:/opt/airflow/scripts
      - ./output:/opt/airflow/output
      - ./assets:/opt/airflow/assets
    command: bash -c "      airflow db migrate &&       airflow users create --role Admin --username admin --password admin --firstname Admin --lastname User --email admin@example.com || true &&       airflow webserver &       airflow scheduler"
