version: '3.8'

services:
  airflow:
    build:
      context: .
      dockerfile: docker/airflow.Dockerfile
    container_name: kraken-airflow
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__WEBSERVER__RBAC=True
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./output:/opt/airflow/output
      - ./assets:/opt/airflow/assets
    command: bash -c "\
      airflow db init && \
      airflow users create --role Admin --username admin --password admin --firstname Admin --lastname User --email admin@example.com && \
      airflow webserver -p 8080 & \
      airflow scheduler"


